"""
active_learning_core.py

Core utilities for the generic YOLO active-learning pipeline.

Provides:
  train_model        Train a YOLO model on a given dataset directory.
  predict_to_dataset Auto-label images with an existing model into a dataset folder.
  write_dataset_yaml Write/update the dataset.yaml required by Ultralytics.
  count_labels       Count labeled images in a YOLO dataset directory.
  all_images         Iterate all supported images in a directory tree.
"""
from __future__ import annotations

import shutil
import sys
import time
from dataclasses import dataclass
import hashlib
import json
from pathlib import Path

import cv2
import numpy as np

HERE = Path(__file__).resolve().parent
YOLO_ROOT = HERE.parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from dataset_utils import ensure_yolo_dirs, label_exists_in_dataset, save_labeled  # noqa: E402

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
DEFAULT_CLASS_NAMES = ["blueberry", "strawberry"]
_ASPECT_MAX = 999.0  # unconstrained aspect ratio sentinel


@dataclass
class StageStats:
    name: str
    model_path: str = ""
    labeled: int = 0
    auto_accepted: int = 0
    auto_accept_audit: int = 0
    needs_review: int = 0
    skipped: int = 0
    low_conf: int = 0
    missed_list: str = ""
    missed_dir: str = ""
    auto_accept_report: str = ""
    seconds: float = 0.0


def read_image(path: Path) -> np.ndarray | None:
    raw = np.fromfile(str(path), dtype=np.uint8)
    return cv2.imdecode(raw, cv2.IMREAD_COLOR)


def all_images(images_dir: Path) -> list[Path]:
    return sorted(p for p in images_dir.iterdir() if p.is_file() and p.suffix.lower() in IMAGE_EXTS)


def count_labels(dataset_dir: Path) -> int:
    return sum(1 for split in ("train", "val") for _ in (dataset_dir / split / "labels").glob("*.txt"))


def collect_device_info(requested_device: str) -> dict[str, object]:
    info: dict[str, object] = {
        "requested_device": requested_device if requested_device else "auto",
        "torch_available": False,
        "cuda_available": False,
        "cuda_device_count": 0,
        "selected_note": "cpu/fallback",
    }
    try:
        import torch

        info["torch_available"] = True
        info["torch_version"] = torch.__version__
        info["cuda_available"] = bool(torch.cuda.is_available())
        info["cuda_device_count"] = int(torch.cuda.device_count()) if torch.cuda.is_available() else 0
        if torch.cuda.is_available():
            current = torch.cuda.current_device()
            info["cuda_current_device"] = int(current)
            info["cuda_device_name"] = torch.cuda.get_device_name(current)
            info["selected_note"] = "cuda/gpu"
    except Exception as exc:
        info["error"] = str(exc)
    return info


def print_device_info(info: dict[str, object]) -> None:
    print("\n[GPU] Device check")
    print(f"  requested device : {info.get('requested_device')}")
    print(f"  torch available  : {info.get('torch_available')}")
    print(f"  torch version    : {info.get('torch_version', 'unknown')}")
    print(f"  cuda available   : {info.get('cuda_available')}")
    print(f"  cuda devices     : {info.get('cuda_device_count')}")
    if info.get("cuda_device_name"):
        print(f"  gpu name         : {info.get('cuda_device_name')}")
    print(f"  selected note    : {info.get('selected_note')}")
    if info.get("error"):
        print(f"  device error     : {info.get('error')}")


def write_dataset_yaml(dataset_dir: Path, class_names: list[str] | None = None) -> Path:
    """Write an Ultralytics-friendly YAML with an absolute root path."""
    ensure_yolo_dirs(dataset_dir)
    names = class_names or DEFAULT_CLASS_NAMES
    yaml_path = dataset_dir / "dataset.yaml"
    names_block = "\n".join(f"  {i}: {name}" for i, name in enumerate(names))
    yaml_path.write_text(
        "# Auto-generated by active_learning_core.py\n"
        f"path: \"{dataset_dir.resolve().as_posix()}\"\n"
        "train: train/images\n"
        "val: val/images\n\n"
        f"nc: {len(names)}\n"
        f"names:\n{names_block}\n",
        encoding="utf-8",
    )
    return yaml_path


def resolve_model(model_name: str) -> str:
    model_path = Path(model_name)
    if model_path.exists():
        return str(model_path.resolve())
    local = YOLO_ROOT / model_name
    return str(local.resolve()) if local.exists() else model_name


def latest_best(project: Path, run_name: str | None = None) -> str:
    search_root = project / run_name if run_name else project
    candidates = sorted(search_root.rglob("best.pt"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not candidates and run_name:
        candidates = sorted(project.rglob("best.pt"), key=lambda p: p.stat().st_mtime, reverse=True)
    return str(candidates[0].resolve()) if candidates else ""


_DEVICE_INFO_PRINTED: set[str] = set()


def train_model(
    dataset_dir: Path,
    base_model: str,
    project: Path,
    name: str,
    epochs: int,
    imgsz: int = 640,
    batch: int = 8,
    device: str = "",
    class_names: list[str] | None = None,
    freeze: int = 10,
) -> str:
    try:
        import torch
        from ultralytics import YOLO
    except ImportError as exc:
        raise SystemExit(
            "Missing ultralytics/torch. Run the BAT file so dependencies can be checked or installed.\n"
            f"detail: {exc}"
        )

    yaml_path = write_dataset_yaml(dataset_dir, class_names)
    if count_labels(dataset_dir) == 0:
        raise SystemExit(f"No labels available for training: {dataset_dir}")

    device_key = device if device else "auto"
    if device_key not in _DEVICE_INFO_PRINTED:
        print_device_info(collect_device_info(device))
        _DEVICE_INFO_PRINTED.add(device_key)
    model = YOLO(resolve_model(base_model))
    model.train(
        data=str(yaml_path.resolve()),
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        project=str(project.resolve()),
        name=name,
        exist_ok=True,
        device=device,
        freeze=freeze,
        cache="ram",
        workers=0,
        amp=bool(torch.cuda.is_available()),
        rect=True,
        patience=10,
        plots=True,
        save_period=-1,
        degrees=12,
        scale=0.35,
        fliplr=0.5,
        flipud=0.0,
        hsv_s=0.35,
        hsv_v=0.35,
    )

    best = latest_best(project, name)
    if not best:
        raise SystemExit(f"Could not find best.pt after training: {project / name}")
    return best


def yolo_line_from_xyxy(cls: int, xyxy: tuple[float, float, float, float], w: int, h: int) -> str:
    x1, y1, x2, y2 = xyxy
    x1 = max(0.0, min(float(w - 1), x1))
    x2 = max(0.0, min(float(w - 1), x2))
    y1 = max(0.0, min(float(h - 1), y1))
    y2 = max(0.0, min(float(h - 1), y2))
    if x2 < x1:
        x1, x2 = x2, x1
    if y2 < y1:
        y1, y2 = y2, y1
    return (
        f"{cls} {(x1 + x2) / 2 / w:.6f} {(y1 + y2) / 2 / h:.6f} "
        f"{(x2 - x1) / w:.6f} {(y2 - y1) / h:.6f}"
    )


def _hash_ratio(text: str) -> float:
    digest = hashlib.sha1(text.encode("utf-8")).hexdigest()
    return int(digest[:8], 16) / 0xFFFFFFFF


def _box_iou(a: tuple[float, float, float, float], b: tuple[float, float, float, float]) -> float:
    ax1, ay1, ax2, ay2 = a
    bx1, by1, bx2, by2 = b
    ix1, iy1 = max(ax1, bx1), max(ay1, by1)
    ix2, iy2 = min(ax2, bx2), min(ay2, by2)
    iw, ih = max(0.0, ix2 - ix1), max(0.0, iy2 - iy1)
    inter = iw * ih
    area_a = max(0.0, ax2 - ax1) * max(0.0, ay2 - ay1)
    area_b = max(0.0, bx2 - bx1) * max(0.0, by2 - by1)
    union = area_a + area_b - inter
    return inter / union if union > 0 else 0.0


def _auto_accept_decision(
    *,
    image_stem: str,
    boxes: list,
    img: np.ndarray,
    model,
    conf: float,
    rules: dict[str, object],
) -> tuple[bool, bool, str, dict[str, float]]:
    if not boxes:
        return False, False, "no_box", {}

    threshold = rules.get("confidence")
    if threshold is None:
        return False, False, "disabled", {}

    require_single = bool(rules.get("require_single_detection", True))
    if require_single and len(boxes) != 1:
        return False, False, "multiple_boxes", {"box_count": float(len(boxes))}

    box = boxes[0]
    score = float(box.conf[0])
    if score < float(threshold):
        return False, False, "low_confidence", {"confidence": score}

    h, w = img.shape[:2]
    x1, y1, x2, y2 = (float(v) for v in box.xyxy[0])
    bw = max(0.0, x2 - x1) / max(1, w)
    bh = max(0.0, y2 - y1) / max(1, h)
    area = bw * bh
    aspect = bw / bh if bh > 0 else _ASPECT_MAX
    metrics = {
        "confidence": score,
        "area_ratio": area,
        "aspect_ratio": aspect,
        "box_count": float(len(boxes)),
    }

    min_area = float(rules.get("min_area_ratio", 0.0))
    max_area = float(rules.get("max_area_ratio", 1.0))
    min_aspect = float(rules.get("min_aspect_ratio", 0.0))
    max_aspect = float(rules.get("max_aspect_ratio", _ASPECT_MAX))
    if area < min_area:
        return False, False, "area_too_small", metrics
    if area > max_area:
        return False, False, "area_too_large", metrics
    if aspect < min_aspect:
        return False, False, "aspect_too_narrow", metrics
    if aspect > max_aspect:
        return False, False, "aspect_too_wide", metrics

    consistency_iou = float(rules.get("consistency_iou", 0.0) or 0.0)
    if consistency_iou > 0:
        flipped = cv2.flip(img, 1)
        flipped_result = model.predict(flipped, conf=conf, verbose=False)[0]
        flipped_boxes = sorted(flipped_result.boxes, key=lambda b: float(b.conf[0]), reverse=True)
        if not flipped_boxes:
            return False, False, "consistency_no_box", metrics
        fx1, fy1, fx2, fy2 = (float(v) for v in flipped_boxes[0].xyxy[0])
        unflipped = (w - fx2, fy1, w - fx1, fy2)
        iou = _box_iou((x1, y1, x2, y2), unflipped)
        metrics["consistency_iou"] = iou
        if iou < consistency_iou:
            return False, False, "consistency_low_iou", metrics

    audit_ratio = max(0.0, min(1.0, float(rules.get("audit_ratio", 0.0) or 0.0)))
    audit = _hash_ratio(image_stem) < audit_ratio
    return True, audit, "auto_accept_audit" if audit else "auto_accept", metrics


def _merge_review_status(dataset_dir: Path, updates: dict[str, bool]) -> None:
    if not updates:
        return
    status_path = dataset_dir / "review_status.json"
    try:
        existing = json.loads(status_path.read_text(encoding="utf-8")) if status_path.exists() else {}
    except json.JSONDecodeError:
        existing = {}
    existing.update(updates)
    status_path.write_text(json.dumps(existing, ensure_ascii=False, indent=2), encoding="utf-8")


def predict_to_dataset(
    images_dir: Path,
    dataset_dir: Path,
    model_path: str,
    conf: float,
    val_ratio: float,
    target_class: int | None,
    only_unlabeled: bool,
    top1: bool,
    class_names: list[str] | None = None,
    missed_dir: Path | None = None,
    missed_list_path: Path | None = None,
    auto_accept_rules: dict[str, object] | None = None,
) -> StageStats:
    try:
        from ultralytics import YOLO
    except ImportError as exc:
        raise SystemExit(f"Missing ultralytics: {exc}")

    ensure_yolo_dirs(dataset_dir)
    write_dataset_yaml(dataset_dir, class_names)
    model = YOLO(model_path)

    stats = StageStats(name="predict")
    t0 = time.monotonic()
    targets = all_images(images_dir)
    if only_unlabeled:
        targets = [p for p in targets if not label_exists_in_dataset(p.stem, dataset_dir)]

    missed: list[Path] = []
    review_status_updates: dict[str, bool] = {}
    auto_items: list[dict[str, object]] = []
    reason_counts: dict[str, int] = {}
    if missed_dir:
        if missed_dir.exists():
            shutil.rmtree(missed_dir)
        missed_dir.mkdir(parents=True, exist_ok=True)
        stats.missed_dir = str(missed_dir.resolve())
    if missed_list_path:
        missed_list_path.parent.mkdir(parents=True, exist_ok=True)
        stats.missed_list = str(missed_list_path.resolve())

    print(f"[Predict] target images={len(targets)} only_unlabeled={only_unlabeled} conf={conf}")
    if auto_accept_rules and float(auto_accept_rules.get("consistency_iou", 0.0) or 0.0) > 0:
        print(f"[Predict] consistency_iou enabled — each labeled image runs a second flip inference (2× slower)")
    for i, img_path in enumerate(targets, start=1):
        img = read_image(img_path)
        if img is None:
            stats.skipped += 1
            missed.append(img_path)
            continue

        result = model.predict(img, conf=conf, verbose=False)[0]
        if not result.boxes:
            stats.low_conf += 1
            missed.append(img_path)
            continue

        h, w = img.shape[:2]
        original_boxes = sorted(result.boxes, key=lambda b: float(b.conf[0]), reverse=True)
        boxes = list(original_boxes)
        if top1:
            boxes = boxes[:1]

        lines: list[str] = []
        for box in boxes:
            cls = target_class if target_class is not None else int(box.cls[0])
            if class_names is not None and (cls < 0 or cls >= len(class_names)):
                continue
            lines.append(yolo_line_from_xyxy(cls, tuple(float(v) for v in box.xyxy[0]), w, h))
        if not lines:
            stats.low_conf += 1
            missed.append(img_path)
            continue
        save_labeled(img, lines, img_path.stem, dataset_dir, val_ratio)
        stats.labeled += 1

        if auto_accept_rules:
            accepted, audit, reason, metrics = _auto_accept_decision(
                image_stem=img_path.stem,
                boxes=original_boxes,
                img=img,
                model=model,
                conf=conf,
                rules=auto_accept_rules,
            )
            reason_counts[reason] = reason_counts.get(reason, 0) + 1
            if accepted and not audit:
                stats.auto_accepted += 1
                review_status_updates[img_path.stem] = True
            else:
                stats.needs_review += 1
                if audit:
                    stats.auto_accept_audit += 1
                review_status_updates[img_path.stem] = False
            auto_items.append(
                {
                    "stem": img_path.stem,
                    "accepted": accepted,
                    "audit": audit,
                    "reason": reason,
                    **metrics,
                }
            )

        if i % 25 == 0 or i == len(targets):
            print(f"  [{i:4d}/{len(targets):4d}] saved={stats.labeled} low_conf={stats.low_conf}")

    stats.seconds = time.monotonic() - t0
    if auto_accept_rules:
        _merge_review_status(dataset_dir, review_status_updates)
        report = {
            "dataset": str(dataset_dir.resolve()),
            "rules": auto_accept_rules,
            "labeled": stats.labeled,
            "auto_accepted": stats.auto_accepted,
            "auto_accept_audit": stats.auto_accept_audit,
            "needs_review": stats.needs_review,
            "reason_counts": reason_counts,
            "items": auto_items,
        }
        report_path = dataset_dir / "auto_accept_report.json"
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
        stats.auto_accept_report = str(report_path.resolve())
        print(
            f"[auto_accept] accepted={stats.auto_accepted} "
            f"audit={stats.auto_accept_audit} needs_review={stats.needs_review} report={report_path}"
        )
    if missed_dir:
        for src in missed:
            if src.exists():
                shutil.copy2(src, missed_dir / src.name)
    if missed_list_path:
        missed_list_path.write_text("\n".join(str(p.resolve()) for p in missed), encoding="utf-8")
    if missed:
        print(f"[Predict] missed images={len(missed)}")
        if missed_dir:
            print(f"  missed dir : {missed_dir}")
        if missed_list_path:
            print(f"  missed list: {missed_list_path}")
    return stats


if __name__ == "__main__":
    raise SystemExit("active_learning_core.py is a utility module. Run RUN_RESEARCH_PIPELINE.bat or research_pipeline.py instead.")
